64 : checkLogicalOperatorAfterSpace:next
105 : checkLogicalOperatorAfterSpace:next
140 : checkLogicalOperatorAfterSpace:next
157 : checkLogicalOperatorAfterSpace:next
160 : checkLogicalOperatorAfterSpace:next
161 : checkLogicalOperatorAfterSpace:next
162 : checkLogicalOperatorAfterSpace:next
163 : checkLogicalOperatorAfterSpace:next
165 : checkLogicalOperatorAfterSpace:next
177 : checkLogicalOperatorAfterSpace:next
210 : checkLogicalOperatorAfterSpace:next
221 : checkLogicalOperatorAfterSpace:next
228 : checkLogicalOperatorAfterSpace:next
230 : checkLogicalOperatorAfterSpace:next
295 : checkLogicalOperatorAfterSpace:next
301 : checkLogicalOperatorAfterSpace:next
377 : checkLogicalOperatorAfterSpace:next
383 : checkLogicalOperatorAfterSpace:next
429 : checkLogicalOperatorAfterSpace:next
432 : checkLogicalOperatorAfterSpace:next
432 : checkLogicalOperatorAfterSpace:next
435 : checkLogicalOperatorAfterSpace:next
448 : checkLogicalOperatorAfterSpace:next
448 : checkLogicalOperatorAfterSpace:next
451 : checkMiddleBracket:prev
451 : checkMiddleBracket:next
459 : checkLogicalOperatorAfterSpace:next
459 : checkLogicalOperatorAfterSpace:next
482 : checkLogicalOperatorAfterSpace:next
485 : checkLogicalOperatorAfterSpace:next
488 : checkMiddleBracket:prev
488 : checkLogicalOperatorAfterSpace:next
488 : checkLogicalOperatorAfterSpace:next
528 : checkLogicalOperatorAfterSpace:next
529 : checkLogicalOperatorAfterSpace:next
530 : checkLogicalOperatorAfterSpace:next
531 : checkOtherBracket : < 
531 : checkLogicalOperatorAfterSpace:next
532 : checkLogicalOperatorAfterSpace:next
534 : checkLogicalOperatorAfterSpace:next
539 : checkLogicalOperatorAfterSpace:next
539 : checkLogicalOperatorAfterSpace:next
544 : checkLogicalOperatorAfterSpace:next
556 : checkLogicalOperatorAfterSpace:next
556 : checkLogicalOperatorAfterSpace:next
580 : checkLogicalOperatorAfterSpace:next
580 : checkLogicalOperatorAfterSpace:next
584 : checkLogicalOperatorAfterSpace:next
584 : checkLogicalOperatorAfterSpace:next
628 : checkLogicalOperatorAfterSpace:next
645 : checkLogicalOperatorAfterSpace:next
653 : checkOtherBracket : < 
660 : checkOtherBracket : < 
669 : checkOtherBracket : < 
680 : checkOtherBracket : ( 
684 : checkLogicalOperatorAfterSpace:next
688 : checkLogicalOperatorAfterSpace:next
688 : checkLogicalOperatorAfterSpace:next
692 : checkLogicalOperatorAfterSpace:next
692 : checkLogicalOperatorAfterSpace:next
697 : checkLogicalOperatorAfterSpace:next
710 : checkMiddleBracket:prev
710 : checkMiddleBracket:next
718 : checkLogicalOperatorAfterSpace:next
718 : checkLogicalOperatorAfterSpace:next
719 : checkMiddleBracket:prev
719 : checkMiddleBracket:next
738 : checkLogicalOperatorAfterSpace:next
755 : checkLogicalOperatorAfterSpace:next
775 : checkMiddleBracket:prev
775 : checkMiddleBracket:next
785 : checkLogicalOperatorAfterSpace:next
786 : checkMiddleBracket:prev
786 : checkMiddleBracket:next
827 : checkMiddleBracket:prev
827 : checkMiddleBracket:next
837 : checkLogicalOperatorAfterSpace:next
838 : checkMiddleBracket:prev
838 : checkMiddleBracket:next
